[project]
name = "ecommerce-mcp-server"
version = "0.1.0"
description = "Model Context Protocol (MCP) server for e-commerce product service integration"
readme = "README.md"
authors = [
    { name = "Satyajit Linka", email = "satyajitlinka@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastmcp>=4.0.10",
    "httpx>=0.28.1",
    "pydantic>=2.10.0",
    "pyjwt>=2.10.0",
]

[project.scripts]
ecommerce-mcp-server = "ecommerce_mcp_server:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"
